<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><meta name="robots" content="noindex,nofollow" /><title>Customers Email Review - Highlights Travel</title></head><style>@import url('https://fonts.googleapis.com/css?family=Courgette');p { font-size:14px; line-height:22px; margin-bottom:10px;}a { color:#555;}ul { margin-left:10px; padding-left:15px;}li { list-style: none; font-size:14px; line-height:18px; margin-bottom:10px; color:#000}li strong { font-weight: normal; color:#999;}</style><body style="color: #333; margin: 20px 0px; padding: 0px; font-family: Verdana, Geneva, sans-serif; font-size: 12px;"><div style="width:752px; display: block; background:#e8e8e8; padding:12px; margin:25px auto 10px; overflow: hidden;"<div class="ahInfo" style="background:#fff; width:357px; display: block; float: left; border-right: 1px solid #d1d1d1; padding:35px 25px; height:395px; position:relative;"><span style="display: block; margin-bottom:25px; color:#a31022;font-family: 'Segoe Print',Verdana, Geneva, sans-serif; font-size:24px;">Thank you for your inquiry.</span><p>One of our specialists will go through your travel plan and contact you within 24 hours. </p<p>Here is a general frame of your inquiry. Let us know if it is incorrect or you need to make any changes.</p>
<p>Thank you once again for choosing Highlights Travel. </p><p>Kind Regards,</p><span style="font-family: 'Segoe Print',Verdana, Geneva, sans-serif; display: block; font-size:18px; margin:25px 0; display: block;">Highlights Travel Team</span><span style=" display: block; margin:40px 0 10px;"><a href="//www.highlightstravel.com">www.highlightstravel.com</a></span><div style=" display: block; position:absolute; right:25px; bottom:35px;"><img src="https://data.highlightstravel.com/pic/logo-104.png"></div></div><div class="customerInfo" style=" background:#f8f8f8; height:100%; display: block; width:314px; float: right; padding:35px 15px 15px; height:415px;"><ul><li style="font-size:18px; display: block; margin:10px 0 15px;">Your travel plans</li><li><strong>Destination(s):</strong><?php $destinationstr = '';
if(!empty($this->input->post('destination'))){ foreach ($this->input->post('destination') as $destination){
	$destinationstr .= $destination.',';
}$destinationstr = substr($destinationstr,0,strlen($destinationstr)-1);echo $destinationstr; }else{echo ''; } ?></li><li><strong>Hotel style:</strong><?php echo $this->input->post('hotel');?></li><li><strong>Group size:</strong><?php echo $this->input->post('adultnumber').' adults,'.$this->input->post('kidnumber').' child';?></li><li><strong>Date of arrival:</strong><?Php 
	if(empty($this->input->post('Date_Start'))){
		echo $this->input->post('Date_Start_Mobile');
	}else{
		echo $this->input->post('Date_Start');
	}
	?></li><li><strong>Trip Length:</strong><?php echo $this->input->post('cli_days'); ?></li><li><strong>Additional requirement:</strong><?php echo $this->input->post('additionalrequirements'); ?></li><li style="font-size:18px; display: block; margin:40px 0 15px;">Your details</li><li><strong>Full name:</strong> <?php echo $this->input->post('name')?></li><li><strong>Email address:</strong><?php echo $this->input->post('email')?></li><li><strong>Phone No.: </strong> <?php echo $this->input->post('PhoneNo')?></li></ul></div></div><div style="width:740px; display: block; padding:12px; margin:10px auto 40px; overflow: hidden; color:#555; line-height:20px;">If you have not received a reply within 24 hours, please check your "junk mail" folder. <br />Or email <a href="mailto:contact@highlightstravel.com">contact@highlightstravel.com</a> and we will investigate the case.</div></body></html>
